# Generated by Django 2.1.5 on 2020-12-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20201212_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='no_img.png', null=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
